import {
  UserProfile,
  DocumentItem,
  CertificateItem,
  ProjectItem,
  PresentationItem,
  AchievementItem,
  EducationItem,
  SkillItem,
  ResumeVersion,
  ImportantLink,
  ActivityLog,
  AppliedHackathon,
  AppliedScholarship,
} from '../types/sagarinfo';

export const initialProfile: UserProfile = {
  id: 'sagar-profile-01',
  fullName: 'Sagar',
  tagline: 'Everything about me. One place.',
  bio: 'Full Stack & AI Engineer passionate about building scalable web applications, intelligent agents, and high-impact digital products.',
  email: 'sagar@example.com',
  phone: '+91 98765 43210',
  location: 'Hyderabad, India',
  education: 'B.Tech in Computer Science & Engineering',
  currentStatus: 'Building Next-Gen AI Applications & Open Source',
  careerGoal: 'Architecting intelligent enterprise systems and founding innovative tech ventures.',
  interests: ['Artificial Intelligence', 'Full Stack Development', 'System Architecture', 'UI/UX Design', 'Hackathons'],
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
  linkedin: 'https://linkedin.com/in/sagar-dev',
  github: 'https://github.com/sagar-dev',
  twitter: 'https://x.com/sagar_tech',
  website: 'https://sagarinfo.dev',
  isPublicProfile: true,
};

export const initialDocuments: DocumentItem[] = [
  {
    id: 'doc-001',
    title: 'Aadhaar Card (Official ID)',
    category: 'identity',
    fileName: 'Aadhaar_Card_Sagar_Verified.pdf',
    fileSize: '1.4 MB',
    fileSizeBytes: 1468006,
    fileType: 'pdf',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    previewUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=800&q=80',
    uploadDate: '2026-01-15',
    description: 'Government issued unique identity card for official KYC verification.',
    tags: ['Identity', 'Government', 'KYC', 'Official'],
    isFavorite: true,
    isPrivate: true,
  },
  {
    id: 'doc-002',
    title: 'PAN Card Digital Copy',
    category: 'identity',
    fileName: 'PAN_Card_Sagar.png',
    fileSize: '850 KB',
    fileSizeBytes: 870400,
    fileType: 'png',
    fileUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=800&q=80',
    previewUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=800&q=80',
    uploadDate: '2026-01-18',
    description: 'Permanent Account Number card for financial and tax identity.',
    tags: ['Tax', 'PAN', 'Identity', 'Financial'],
    isFavorite: false,
    isPrivate: true,
  },
  {
    id: 'doc-003',
    title: 'B.Tech Consolidated Marksheet & Degree',
    category: 'education',
    fileName: 'BTech_Degree_Consolidated_Marksheet.pdf',
    fileSize: '3.2 MB',
    fileSizeBytes: 3355443,
    fileType: 'pdf',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    previewUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=800&q=80',
    uploadDate: '2026-02-10',
    description: 'Official university degree transcript showing 8.9 CGPA overall.',
    tags: ['Education', 'Degree', 'Marksheet', 'B.Tech'],
    isFavorite: true,
    isPrivate: false,
  },
  {
    id: 'doc-004',
    title: 'Intermediate (12th Class) Certificate',
    category: 'education',
    fileName: 'Intermediate_MPC_Marksheet_96.5.pdf',
    fileSize: '1.8 MB',
    fileSizeBytes: 1887436,
    fileType: 'pdf',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    previewUrl: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?auto=format&fit=crop&w=800&q=80',
    uploadDate: '2025-11-20',
    description: '12th Grade Board Certificate (MPC Branch - 96.5%).',
    tags: ['12th', 'Board', 'Education', 'Certificate'],
    isFavorite: false,
    isPrivate: false,
  },
  {
    id: 'doc-005',
    title: 'SSC 10th Class Board Certificate',
    category: 'education',
    fileName: 'SSC_10th_Grade_Certificate.pdf',
    fileSize: '1.1 MB',
    fileSizeBytes: 1153433,
    fileType: 'pdf',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    previewUrl: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?auto=format&fit=crop&w=800&q=80',
    uploadDate: '2025-10-12',
    description: 'Secondary School Certificate 10th grade pass record (9.8 CGPA).',
    tags: ['10th', 'SSC', 'Education'],
    isFavorite: false,
    isPrivate: false,
  },
  {
    id: 'doc-006',
    title: 'Sagar Primary Resume - 2026 AI & FullStack',
    category: 'career',
    fileName: 'Sagar_Resume_2026_FullStack_AI.pdf',
    fileSize: '420 KB',
    fileSizeBytes: 430080,
    fileType: 'pdf',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    previewUrl: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?auto=format&fit=crop&w=800&q=80',
    uploadDate: '2026-03-01',
    description: 'Updated resume emphasizing React, TypeScript, Python, AI APIs, and Supabase.',
    tags: ['Resume', 'Career', 'CV', 'Featured'],
    isFavorite: true,
    isPrivate: false,
  },
  {
    id: 'doc-007',
    title: 'AI Engineering Internship Offer Letter',
    category: 'career',
    fileName: 'AI_Internship_Offer_Letter_Signed.pdf',
    fileSize: '980 KB',
    fileSizeBytes: 1003520,
    fileType: 'pdf',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    previewUrl: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=800&q=80',
    uploadDate: '2026-02-05',
    description: 'Official offer letter for AI Software Engineer Internship role.',
    tags: ['Career', 'Internship', 'Offer Letter'],
    isFavorite: false,
    isPrivate: true,
  },
  {
    id: 'doc-008',
    title: 'Bank Statement & Passbook Copy',
    category: 'financial',
    fileName: 'HDFC_Bank_Passbook_Statement.pdf',
    fileSize: '2.5 MB',
    fileSizeBytes: 2621440,
    fileType: 'pdf',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    previewUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80',
    uploadDate: '2026-02-28',
    description: 'Bank passbook front page and verified account statement.',
    tags: ['Financial', 'Bank', 'HDFC', 'Passbook'],
    isFavorite: false,
    isPrivate: true,
  },
];

export const initialCertificates: CertificateItem[] = [
  {
    id: 'cert-001',
    title: 'AWS Certified Solutions Architect – Associate',
    issuingOrganization: 'Amazon Web Services (AWS)',
    issueDate: '2026-01-20',
    credentialId: 'AWS-ASA-9948271',
    credentialUrl: 'https://aws.amazon.com/verification',
    verificationUrl: 'https://aws.amazon.com/verification?id=AWS-ASA-9948271',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    imageUrl: 'https://images.unsplash.com/photo-1607799279861-4dd421887fb3?auto=format&fit=crop&w=800&q=80',
    skills: ['AWS', 'Cloud Architecture', 'Serverless', 'S3', 'Lambda', 'EC2'],
    description: 'Validated expert ability to design distributed cloud infrastructure on AWS.',
    tags: ['Cloud', 'AWS', 'Architecture', 'Certified'],
    isFavorite: true,
  },
  {
    id: 'cert-002',
    title: 'Meta Full-Stack Developer Professional Certificate',
    issuingOrganization: 'Coursera / Meta',
    issueDate: '2025-11-15',
    credentialId: 'META-FS-881920',
    credentialUrl: 'https://coursera.org/verify/META-FS-881920',
    verificationUrl: 'https://coursera.org/verify/META-FS-881920',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    imageUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=800&q=80',
    skills: ['React', 'JavaScript', 'HTML5', 'CSS3', 'Django', 'REST APIs', 'Git'],
    description: 'Comprehensive 9-course professional specialization covering modern frontend & backend.',
    tags: ['Full Stack', 'Meta', 'React', 'Web Development'],
    isFavorite: true,
  },
  {
    id: 'cert-003',
    title: 'Google Cloud Generative AI Leader',
    issuingOrganization: 'Google Cloud Platform',
    issueDate: '2026-02-01',
    credentialId: 'GCP-GAI-552194',
    credentialUrl: 'https://cloud.google.com/credentials',
    verificationUrl: 'https://cloud.google.com/credentials/verify',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
    skills: ['Generative AI', 'Gemini APIs', 'Prompt Engineering', 'LLM Fine-Tuning'],
    description: 'Demonstrated mastery in deploying Generative AI models and LLM agentic workflows.',
    tags: ['AI', 'Google Cloud', 'Generative AI', 'LLM'],
    isFavorite: true,
  },
];

export const initialProjects: ProjectItem[] = [
  {
    id: 'proj-001',
    name: 'AgriSage AI',
    shortDescription: 'AI-powered intelligent farming assistant providing real-time crop disease detection & yield analytics.',
    detailedDescription: 'AgriSage AI is a comprehensive precision agriculture application that utilizes computer vision to diagnose crop diseases from leaves, integrates hyper-local weather forecasting, and delivers actionable soil health advice powered by Gemini 3.5 AI APIs.',
    category: 'AI & Automation',
    technologies: ['React', 'TypeScript', 'Python', 'FastAPI', 'PyTorch', 'Tailwind CSS', 'Supabase'],
    githubUrl: 'https://github.com/sagar-dev/agrisage-ai',
    liveUrl: 'https://agrisage-ai.demo.app',
    demoVideoUrl: 'https://youtube.com/watch?v=demo',
    presentationUrl: 'https://agrisage-ai.demo.app/presentation.pdf',
    documentationUrl: 'https://github.com/sagar-dev/agrisage-ai#readme',
    screenshots: [
      'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1574943320219-553eb213f72d?auto=format&fit=crop&w=1000&q=80'
    ],
    status: 'Completed',
    startDate: '2025-10-01',
    endDate: '2026-01-15',
    teamMembers: ['Sagar (Lead AI & FullStack)', 'Priya (Data Science)', 'Rahul (UI/UX)'],
    hackathonName: 'National Agri-Tech Innovation Hackathon 2025',
    achievement: '🏆 1st Place Winner - Best AI Solution',
    problemStatement: 'Farmers suffer up to 35% crop loss annually due to late detection of plant diseases and unoptimized fertilizer usage.',
    solution: 'Built an instant smartphone scanner that diagnoses crop diseases in under 2 seconds offline/online and predicts optimal harvesting dates.',
    features: [
      'Instant Computer Vision leaf disease scanner',
      'AI Multilingual Voice Assistant in regional Indian languages',
      'Automated Weather Alerting & Soil Moisture telemetry',
      'Direct Market Price forecasting graph'
    ],
    architectureOverview: 'React frontend hosted on Vercel communicating via REST API with a Python FastAPI microservice deployed on AWS ECS container with PyTorch model inferencing.',
    isFavorite: true,
    isPublic: true,
  },
  {
    id: 'proj-002',
    name: 'SAGARINFO Vault OS',
    shortDescription: 'Next-generation personal digital vault, document manager, project hub & identity operating system.',
    detailedDescription: 'SAGARINFO is a production-grade personal information management suite built with React, Vite, Tailwind CSS, and Supabase. It provides document security, encrypted document storage, resume management, project case studies, global command search (Ctrl+K), and optional public developer portfolio mode.',
    category: 'Full Stack',
    technologies: ['React', 'TypeScript', 'Vite', 'Tailwind CSS', 'Supabase', 'Lucide Icons'],
    githubUrl: 'https://github.com/sagar-dev/sagarinfo',
    liveUrl: 'https://sagarinfo.dev',
    documentationUrl: 'https://github.com/sagar-dev/sagarinfo#readme',
    screenshots: [
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1000&q=80',
      'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1000&q=80'
    ],
    status: 'Completed',
    startDate: '2026-02-01',
    endDate: '2026-03-02',
    teamMembers: ['Sagar (Solo Architect & Developer)'],
    problemStatement: 'Managing personal documents, education records, hackathon awards, project repos, and credentials across multiple cloud drives and folders is fragmented and insecure.',
    solution: 'Designed a unified high-aesthetic personal OS dashboard that organizes all digital assets into one lightning-fast searchable platform.',
    features: [
      'Secure categorized Document Vault with PDF/Image previewer',
      'Command Palette (Ctrl + K) instant global search',
      'Dual Private Vault vs Public Portfolio mode',
      'Certificate manager with verification URLs',
      'Interactive Resume & Skills management matrix'
    ],
    architectureOverview: 'Vite React TypeScript SPA using Supabase Postgres RLS, custom CSS design tokens, and LocalStorage instant fallback state sync.',
    isFavorite: true,
    isPublic: true,
  },
  {
    id: 'proj-003',
    name: 'CodePulse Developer Analytics',
    shortDescription: 'Real-time telemetry dashboard for monitoring Git repositories, PR review speed, and code velocity.',
    detailedDescription: 'CodePulse hooks into GitHub Webhooks to render sleek velocity charts, commit heatmaps, pull request review latency, and automated code review summaries using LLMs.',
    category: 'DevOps & Tools',
    technologies: ['TypeScript', 'Node.js', 'Express', 'React', 'Chart.js', 'PostgreSQL'],
    githubUrl: 'https://github.com/sagar-dev/codepulse',
    liveUrl: 'https://codepulse.dev',
    screenshots: [
      'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?auto=format&fit=crop&w=1000&q=80'
    ],
    status: 'Completed',
    startDate: '2025-06-01',
    endDate: '2025-09-15',
    teamMembers: ['Sagar'],
    problemStatement: 'Engineering leads lack real-time visibility into PR bottlenecks and code review delays across microservices.',
    solution: 'Created an event-driven telemetry pipeline with automated GitHub bot integration that summarizes PR code diffs and alerts reviewers.',
    features: ['GitHub Webhook receiver', 'LLM diff summarizer', 'Real-time team performance charts', 'Discord & Slack webhooks'],
    isFavorite: false,
    isPublic: true,
  },
];

export const initialPresentations: PresentationItem[] = [
  {
    id: 'pres-001',
    title: 'AgriSage AI - Pitch Deck & Architecture Overview',
    relatedProjectName: 'AgriSage AI',
    eventOrHackathon: 'National Agri-Tech Innovation Hackathon 2025',
    date: '2025-12-10',
    description: 'Final presentation slides delivered to hackathon jury detailing model precision, user impact, and deployment cost.',
    fileFormat: 'pdf',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    fileSize: '4.8 MB',
    slideCount: 16,
    isFavorite: true,
  },
  {
    id: 'pres-002',
    title: 'Distributed Systems & Microservices in High-Scale Node.js',
    relatedProjectName: 'CodePulse Developer Analytics',
    eventOrHackathon: 'TechTalks Tech Symposium 2025',
    date: '2025-08-22',
    description: 'Technical slide deck covering event queues, Kafka streaming, and caching strategies for high-frequency webhooks.',
    fileFormat: 'pdf',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    fileSize: '6.2 MB',
    slideCount: 24,
    isFavorite: false,
  },
];

export const initialAchievements: AchievementItem[] = [
  {
    id: 'ach-001',
    title: '1st Place Winner - Grand Champion',
    organization: 'Ministry of Agriculture & Tech India',
    date: '2025-12-12',
    description: 'Awarded 1st Place out of 250+ teams nationwide for AgriSage AI project at the National Innovation Hackathon.',
    event: 'National Agri-Tech Innovation Hackathon 2025',
    rankOrResult: '🏆 1st Place Winner',
    certificateUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    relatedProjectName: 'AgriSage AI',
    link: 'https://agrisage-ai.demo.app',
    isFavorite: true,
  },
  {
    id: 'ach-002',
    title: 'Smart India Hackathon Finalist',
    organization: 'AICTE & Ministry of Education',
    date: '2025-09-28',
    description: 'Qualified in Top 10 national teams for building real-time IoT monitoring system for educational campuses.',
    event: 'Smart India Hackathon 2025',
    rankOrResult: '🎖 Top 10 National Finalist',
    certificateUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    isFavorite: true,
  },
  {
    id: 'ach-003',
    title: 'Academic Excellence Award - Department Topper',
    organization: 'University Department of CSE',
    date: '2025-05-15',
    description: 'Honored for maintaining consistent top academic performance (8.9 CGPA) in B.Tech Computer Science.',
    event: 'Annual University Academic Convocation',
    rankOrResult: '🥇 Department Top Rank',
    isFavorite: false,
  },
];

export const initialEducation: EducationItem[] = [
  {
    id: 'edu-001',
    degree: 'B.Tech in Computer Science & Engineering',
    level: 'B.Tech',
    institution: 'University College of Engineering & Technology',
    boardOrUniversity: 'JNTU / AICTE Approved',
    startYear: '2022',
    endYear: '2026',
    score: '8.9 CGPA',
    status: 'Pursuing',
    fieldOfStudy: 'Computer Science & Engineering',
    location: 'Hyderabad, India',
    highlights: [
      'Specialization in Artificial Intelligence & Full Stack Web Development',
      'Lead Developer in College Tech Club',
      'Published 2 research seminar papers on LLM agents'
    ],
    certificateUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  },
  {
    id: 'edu-002',
    degree: 'Intermediate (12th Grade - MPC Branch)',
    level: 'Intermediate',
    institution: 'Narayana Junior College',
    boardOrUniversity: 'Board of Intermediate Education',
    startYear: '2020',
    endYear: '2022',
    score: '96.5%',
    status: 'Completed',
    fieldOfStudy: 'MPC (Mathematics, Physics, Chemistry)',
    location: 'Hyderabad, India',
    highlights: [
      'Secured State Top Percentile in Mathematics (99/100)',
      'Qualified JEE Mains with top rank'
    ],
    certificateUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  },
  {
    id: 'edu-003',
    degree: 'Secondary School Certificate (10th SSC)',
    level: 'School',
    institution: 'St. Paul High School',
    boardOrUniversity: 'State Secondary Board',
    startYear: '2019',
    endYear: '2020',
    score: '9.8 CGPA',
    status: 'Completed',
    fieldOfStudy: 'General Secondary Science & Mathematics',
    location: 'Hyderabad, India',
    highlights: [
      'School Topper in Mathematics & Science Olympiad',
      'Best All-Rounder Student Award'
    ],
    certificateUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  },
];

export const initialSkills: SkillItem[] = [
  { id: 'skill-01', name: 'C++', category: 'Programming', proficiency: 90, yearsOfExperience: '4 yrs', relatedProjectsCount: 5, featured: true },
  { id: 'skill-02', name: 'Python', category: 'Programming', proficiency: 92, yearsOfExperience: '3 yrs', relatedProjectsCount: 8, featured: true },
  { id: 'skill-03', name: 'TypeScript', category: 'Programming', proficiency: 95, yearsOfExperience: '3 yrs', relatedProjectsCount: 12, featured: true },
  { id: 'skill-04', name: 'SQL & PostgreSQL', category: 'Programming', proficiency: 88, yearsOfExperience: '3 yrs', relatedProjectsCount: 6, featured: false },
  { id: 'skill-05', name: 'React & React Native', category: 'Frontend', proficiency: 96, yearsOfExperience: '3 yrs', relatedProjectsCount: 10, featured: true },
  { id: 'skill-06', name: 'Tailwind CSS', category: 'Frontend', proficiency: 94, yearsOfExperience: '3 yrs', relatedProjectsCount: 10, featured: true },
  { id: 'skill-07', name: 'HTML5 & CSS3', category: 'Frontend', proficiency: 98, yearsOfExperience: '4 yrs', relatedProjectsCount: 14, featured: false },
  { id: 'skill-08', name: 'Node.js & Express', category: 'Backend', proficiency: 91, yearsOfExperience: '3 yrs', relatedProjectsCount: 8, featured: true },
  { id: 'skill-09', name: 'MongoDB', category: 'Backend', proficiency: 85, yearsOfExperience: '2 yrs', relatedProjectsCount: 4, featured: false },
  { id: 'skill-10', name: 'Supabase & Firebase', category: 'Backend', proficiency: 92, yearsOfExperience: '2 yrs', relatedProjectsCount: 6, featured: true },
  { id: 'skill-11', name: 'Generative AI & LLM APIs', category: 'AI & ML', proficiency: 90, yearsOfExperience: '2 yrs', relatedProjectsCount: 5, featured: true },
  { id: 'skill-12', name: 'AI Automation & Agents', category: 'AI & ML', proficiency: 86, yearsOfExperience: '1.5 yrs', relatedProjectsCount: 4, featured: true },
  { id: 'skill-13', name: 'Git & GitHub', category: 'Tools & DevOps', proficiency: 95, yearsOfExperience: '4 yrs', relatedProjectsCount: 15, featured: true },
  { id: 'skill-14', name: 'Docker & AWS S3/ECS', category: 'Tools & DevOps', proficiency: 82, yearsOfExperience: '2 yrs', relatedProjectsCount: 4, featured: false },
  { id: 'skill-15', name: 'VS Code & Figma', category: 'Tools & DevOps', proficiency: 95, yearsOfExperience: '4 yrs', relatedProjectsCount: 15, featured: false },
];

export const initialResumeVersions: ResumeVersion[] = [
  {
    id: 'res-v3',
    versionName: 'v3.0 - AI & Full Stack Focus',
    title: 'Sagar_Resume_2026_FullStack_AI.pdf',
    uploadDate: '2026-03-01',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    fileSize: '420 KB',
    isCurrent: true,
    notes: 'Primary active resume tailored for AI Engineering & Senior Full Stack roles.'
  },
  {
    id: 'res-v2',
    versionName: 'v2.1 - Backend & Cloud Focus',
    title: 'Sagar_Resume_2025_Backend_Cloud.pdf',
    uploadDate: '2025-11-10',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    fileSize: '390 KB',
    isCurrent: false,
    notes: 'Focused on Node.js microservices, PostgreSQL, and AWS cloud deployment.'
  },
  {
    id: 'res-v1',
    versionName: 'v1.0 - Internship General Resume',
    title: 'Sagar_Resume_2025_Internship.pdf',
    uploadDate: '2025-06-15',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    fileSize: '350 KB',
    isCurrent: false,
    notes: 'General software developer intern format.'
  }
];

export const initialLinks: ImportantLink[] = [
  {
    id: 'link-01',
    name: 'LinkedIn Profile',
    url: 'https://linkedin.com/in/sagar-dev',
    category: 'Professional',
    description: 'Professional networking profile & connections.',
    iconName: 'Linkedin',
    isFavorite: true,
  },
  {
    id: 'link-02',
    name: 'GitHub Repositories',
    url: 'https://github.com/sagar-dev',
    category: 'Professional',
    description: 'Open source projects, code repos & contributions.',
    iconName: 'Github',
    isFavorite: true,
  },
  {
    id: 'link-03',
    name: 'AgriSage AI Live Demo',
    url: 'https://agrisage-ai.demo.app',
    category: 'Projects',
    description: 'Live deployed web application for AgriSage AI.',
    iconName: 'ExternalLink',
    isFavorite: true,
  },
  {
    id: 'link-04',
    name: 'Personal Contact Mail',
    url: 'mailto:sagar@example.com',
    category: 'Professional',
    description: 'Direct email contact link.',
    iconName: 'Mail',
    isFavorite: false,
  },
  {
    id: 'link-05',
    name: 'X (Twitter) Handle',
    url: 'https://x.com/sagar_tech',
    category: 'Social',
    description: 'Tech thoughts, product updates & AI threads.',
    iconName: 'Twitter',
    isFavorite: false,
  },
  {
    id: 'link-06',
    name: 'Supabase Cloud Console',
    url: 'https://supabase.com/dashboard',
    category: 'Useful',
    description: 'Database & backend administration portal.',
    iconName: 'Database',
    isFavorite: false,
  },
];

export const initialActivities: ActivityLog[] = [
  { id: 'act-01', action: 'Uploaded primary resume', targetName: 'Sagar_Resume_2026_FullStack_AI.pdf', targetType: 'Resume', timestamp: 'Today at 08:30 AM' },
  { id: 'act-02', action: 'Added new project case study', targetName: 'AgriSage AI', targetType: 'Project', timestamp: 'Yesterday at 04:15 PM' },
  { id: 'act-03', action: 'Added Cloud Certificate', targetName: 'AWS Certified Solutions Architect', targetType: 'Certificate', timestamp: '3 days ago' },
  { id: 'act-04', action: 'Uploaded identity document', targetName: 'Aadhaar Card (Official ID)', targetType: 'Document', timestamp: '5 days ago' },
  { id: 'act-05', action: 'Logged hackathon achievement', targetName: '1st Place Winner - Grand Champion', targetType: 'Achievement', timestamp: '1 week ago' },
];

export const initialAppliedHackathons: AppliedHackathon[] = [
  {
    id: 'hack-01',
    name: 'National Agri-Tech Innovation Hackathon 2025',
    organizer: 'Ministry of Agriculture & Tech India',
    applicationDate: '2025-10-05',
    projectSubmitted: 'AgriSage AI',
    status: 'Winner',
    prizePool: '₹5,00,000 + Incubation Support',
    submissionUrl: 'https://agrisage-ai.demo.app',
    proofUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    notes: 'Secured 1st Place overall out of 250+ teams nationwide. Presented leaf disease scanner live to jury.',
    isFavorite: true,
  },
  {
    id: 'hack-02',
    name: 'Smart India Hackathon (SIH) 2025',
    organizer: 'AICTE & Ministry of Education',
    applicationDate: '2025-08-15',
    projectSubmitted: 'SmartCampus IoT Monitoring System',
    status: 'Selected',
    prizePool: '₹1,00,000',
    submissionUrl: 'https://github.com/sagar-dev/smart-campus-iot',
    proofUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    notes: 'Shortlisted for National Grand Finale round at nodal center. Developed IoT water telemetry hardware.',
    isFavorite: true,
  },
  {
    id: 'hack-03',
    name: 'Google Generative AI Global Hackathon 2026',
    organizer: 'Google Cloud & DevPost',
    applicationDate: '2026-01-20',
    projectSubmitted: 'SAGARINFO Vault AI Assistant',
    status: 'Under Review',
    prizePool: '$25,000 USD + Google Cloud Credits',
    submissionUrl: 'https://devpost.com/software/sagarinfo-ai',
    notes: 'Submitted video demo showcasing Gemini 3.5 API document indexing and Ctrl+K search engine.',
    isFavorite: false,
  },
];

export const initialAppliedScholarships: AppliedScholarship[] = [
  {
    id: 'schol-01',
    name: 'Reliance Foundation Undergraduate Scholarship 2025-26',
    provider: 'Reliance Foundation',
    applicationDate: '2025-09-10',
    amount: '₹2,00,000 Total Stipend',
    status: 'Disbursed',
    eligibility: 'B.Tech Undergraduates maintaining >8.5 CGPA & Merit List',
    submittedDocument: 'BTech_Degree_Consolidated_Marksheet.pdf',
    proofUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    notes: 'Selected among top 5,000 scholars across India. First installment disbursed directly to bank account.',
    isFavorite: true,
  },
  {
    id: 'schol-02',
    name: 'National Merit Scholarship for Technical Higher Education',
    provider: 'Ministry of Education & Human Resources',
    applicationDate: '2025-07-01',
    amount: '₹50,000 / Year',
    status: 'Awarded',
    eligibility: 'Top Percentile 12th Board Score (MPC Branch)',
    submittedDocument: 'Intermediate_MPC_Marksheet_96.5.pdf',
    proofUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    notes: 'Awarded based on 96.5% Intermediate board score ranking.',
    isFavorite: true,
  },
  {
    id: 'schol-03',
    name: 'State Government Post-Matric Tech Excellence Award',
    provider: 'Department of Technical Education',
    applicationDate: '2026-02-05',
    amount: '₹35,000 Tuition Reimbursement',
    status: 'Under Review',
    eligibility: 'Pursuing B.Tech Computer Science Degree',
    submittedDocument: 'Aadhaar_Card_Sagar_Verified.pdf',
    notes: 'Application verification pending at college principal desk.',
    isFavorite: false,
  },
];
